### ISSUE TITLE
Install/Setup Issues

### ISSUE THREAD

**Issue by mnkuurst** [cmseaton42/Allen-Bradley-Toolkit#2]
Couldn't find PIA /AB folder under python site-packages. Only installed lxml

**Comment by cmseaton42** [comment]
Is your issue occurring when trying to run `pip install allen-bradley-toolkit`? If so, can you post what error is being thrown on the terminal?

**Comment by cmseaton42** [comment]
Make sure you have [Microsoft Visual C++ Build Tools](http://go.microsoft.com/fwlink/?LinkId=691126&__hstc=268264337.20dfe66f0053415ec618cc41e1e5ebee.1519654047676.1519654047676.1519656772032.2&__hssc=268264337.1.1519656772032&__hsfp=2795554280&fixForIE=.exe) Installed before running `pip install allen-bradley-toolkit`.  Doing this may resolve your issue.  Please let me know if this was helpful or if something else is causing your issue.

**Comment by mnkuurst** [comment]
I initially got the error "setup.py egg_info failed with error code 1" when
installing using pip install.  So I tried installing it locally using *pip
install -e "path to toolkit" * that seemed to be successful except the
package isn't in the site-package folder. Now when I try installing it
using pip install it says it's already there.

I'll try C++ Build tools

**Comment by mnkuurst** [comment]
I tried C++ build tools - It didn't help

If I try to force to reinstall the package with pip install
--force-reinstall, here's the error I got :
[image: Inline image 2]

**Comment by cmseaton42** [comment]
If you run `pip freeze` is *allen-bradley-toolkit* or *lxml* listed? If so, I would go ahead and run `pip uninstall <package>` on those two packages to ensure a clean start.  I checked the install on my PC and got the error you are describing `setup.py egg_info failed with error code 1`. Installing the C++ build tools seemed to fix it as the package installed successfully.  What version of Python are you running?  This package is tested on *Python 2.7*. You may also want to run `pip install --upgrade setuptools` before reinstalling the toolkit.

**Comment by mnkuurst** [comment]
both allen-bradley-toolkit and lxml are listed when running pip freeze.
I'm running version 2.7, I'll try uninstalling, make sure C++ is installed
and install it again see if that works.

Thanks for the help!

Mike

**Comment by cmseaton42** [comment]
Also, I found another bug that resulted from the name change and fixed it so you may need to run `pip install allen-bradley-toolkit -U` to update to the latest version once you do get it installed.

Keep me posted and not a problem!

**Comment by mnkuurst** [comment]
Hi Canaan,

I installed the C++ Build tools and tried installing the allen bradley
toolkit again but am still getting the same error - python setup egg_info
failed with error code 1.

I'm running windows 7, can't think of why it's not working

Mike

**Comment by cmseaton42** [comment]
Hmmm, did you uninstall the instances you had before trying to reinstall?

**Comment by mnkuurst** [comment]
Yeah I uninstalled everything and started from scratch then reinstalled
everything.

Worst case I can just paste the libraries into the site packages folder -
Just wondering if you had an easy solution

**Comment by cmseaton42** [comment]
Can you screenshot the complete error you are getting in the terminal. I am recreating your issue in a windows 7 VM and getting a similar issue.  I want to verify that it is the same one so I can get to the root.

**Comment by cmseaton42** [comment]
I think I fixed the issue... You should be able to install now. If it doesnt work with `pip install allen-bradley-toolkit` then you may need to run with the *ignore cached downloads* flag by running `pip install --no-cache-dir allen-bradley-toolkit`

Let me know if this resolves the issue.

**Comment by mnkuurst** [comment]
It looks like it installed properly. Thanks for looking into it!

**Comment by cmseaton42** [comment]
No problem, The API changed so let me know if have any questions regarding it.  Also, Feel free to request new features via a new issue! Happy Hacking!
